# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener:  true
    allowed_methods_listener:  true
#    routing_loader: true
    view:
        view_response_listener:  true
    exception:
        enabled: true
        codes:
            Doctrine\ORM\EntityNotFoundException: 404
            Doctrine\ORM\NoResultException: 404
            Doctrine\ORM\NonUniqueResultException: 400
        messages:
            Doctrine\ORM\EntityNotFoundException: true
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
            - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: html, prefer_extension: true }
